### ISSUE TITLE
Architectural considerations and pull-requests

### ISSUE THREAD

**Issue by krzysztof-gzocha** [drgomesp/cargo#7]
When I'm looking at the code I've several questions to ask already. I know it's early stage of development, but I guess it might be good to talk about it now than later and since there are no pull-requests to master branch I thought it would be nice to ask those in here. (btw. setting master branch as protected, without merge commits and adding some TravisCI to all PRs would be nice to add)
1. In `container/builder.go` method:
   
   ``` go
   // Register a new service definition
   func (b *Builder) Register(id string, fn interface{}) (builder *Builder, err error)
   ```
   
   is creating a definition based on `fn` inside and is registering this definition into the container.
   Does it really need to care about how to create definition from given `interface{}`?
   I was thinking that it should just receive `id` and `definition` as a parameters. Whole creation of a   definition should be done somewhere else - maybe in `Loader`?
2. There is method `Get` which will fetch service or definition. There is method `GetDefinition` which will fetch definition, but there is no `GetService` method?
3. This file `container/builder.go` is about building the container itself, right? Should it be aware how to create a service basing on its definition? Wouldn't it be better to create `ServiceBuilder` that would have all the required logic to create service from some definition?

**Comment by drgomesp** [comment]
Regarding the creation of definitions, because of the statically typed nature of the language, you can't pass an object literal or a string that will later be evaluated into a type. Therefore there are two ways of defining services. Using composite literal expressions (`&Foo{}`) or constructor function literals (`NewFoo`) 

The `Get` method actually returns the service. 

The builder is not responsible for creating the container, but is rather a wrapper of the container that provides an API for describing services and it uses the underlying container for resolving.

**Comment by drgomesp** [comment]
The idea of a Travis build per PR is a great one. I'll be looking into that. Feel free to contribute as well.

**Comment by krzysztof-gzocha** [comment]
Regarding creation of definitions I've meant to create separate function/service that will create a definition from literal expressions or constructor functions and pass only properly built definition to the builder. My point is that builder is having too much responsibility.
Should be even named builder? ;)

About pull-requests I can see that you already have `.travis.yml`, so I can't really contribute for this, but now it's pretty simple to add Travis CI status checks as required for each pull-requests.
You just need to go to repo settings->integrations->configure travis CI and later to branches and setup master branch as protected (you won't be able to push from CLI to it directly) and mark TravisCI as required status check.

It should look like:
![screen shot 2016-09-24 at 14 15 11](https://cloud.githubusercontent.com/assets/3098559/18807783/61adcf8c-8261-11e6-8409-48ad5b273f6e.png)

Good luck!

**Comment by drgomesp** [comment]
Ok, so what you mean is adding more abstraction, which generally I like. We would end up with something like:

``` go
def := NewDefinition(&Foo{}) 
container.AddDefinition("foo", def) 
```

This would eliminate the builder I guess. What do you think?

**Comment by krzysztof-gzocha** [comment]
![Beauty!](http://31.media.tumblr.com/tumblr_m2f66lfsBv1rtfmbao1_500.gif)

**Comment by drgomesp** [comment]
Closing since it's resolved.
